### ISSUE TITLE
`alphafold3.cpp` Module Not Found During Execution 

### ISSUE THREAD

**Issue by ShiyiLin0922** [google-deepmind/alphafold3#234]
### Question: `alphafold3.cpp` Module Not Found During Execution  

Hello, I am trying to run `run_alphafold.py` from the AlphaFold 3 repository. However, I encountered the following issue:  🥺

```
ModuleNotFoundError: No module named 'alphafold3.cpp'
```  

#### Steps I Followed:  
1. I cloned the repository and set up the environment as described in the installation instructions.  
2. Due to the limitations of cluster permissions, I did not use Docker, but instead configured the dependency packages in a conda environment.
3. Ran the script `run_alphafold.py`.  

#### Observations:  
- The error suggests that the `alphafold3.cpp` module is missing.  
- The repository includes a file named `cpp.cc` under `src/alphafold3/`.  
- However, the installation instructions did not mention compiling this file or how to generate the necessary `.so` module.  

#### File Directory Structure:  

Here is the file structure of the repository (partial):  

```
alphafold3/
├── src/
│   └── alphafold3/
│       ├── __init__.py
│       ├── cpp.cc
│       ├── data/
│       │   └── cpp/
│       ├── structure/
│       │   ├── __init__.py
│       │   ├── bioassemblies.py
│       │   ├── mmcif.py
│       │   ├── cpp/
│       ├── parsers/
│       │   └── cpp/
│       ├── model/
│       ├── constants/
│       └── common/
├── requirements.txt
├── pyproject.toml
├── run_alphafold.py
├── CMakeLists.txt
├── ……
```
Note: I have not made any modifications to the directory structure, so it is identical to the one directly cloned from GitHub.

#### Questions:  🥺
1. Is `cpp.cc` supposed to be compiled into a shared library (e.g., `.so` file)?  If yes, could you clarify the steps to compile it?  
3. Could the manual setup using Conda instead of Docker cause this issue? If so, how can I troubleshoot or resolve it?  
4. Are the current locations of the `cpp.cc` file and other modules correct, or do they need to be moved to a different directory for proper loading and execution?  

Thank you for your help!  🥰

**Comment by alchemistcai** [comment]
I use conda too.Have you run `pip install . --no-deps` after `pip install -r dev-requirements.txt`?

This command copys modules and compiles the cpp into your conda environment.

I wrote a easy install guidance in #49 if you want some help.

**Comment by Augustin-Zidek** [comment]
Hi, what version of the code are you running with -- is it the initial tagged version v3.0.0, or with the latest commit? Also, are you using Python 3.12 or Python 3.11?

The reason I am asking is that we fixed Python 3.12 incompatibility in https://github.com/google-deepmind/alphafold3/commit/23e3d46d4ca126e8731e8c0cbb5673e9a848ceb5, see also https://github.com/google-deepmind/alphafold3/issues/33 for more details.

**Comment by han-bin-liu** [comment]
I ran the code in https://github.com/google-deepmind/alphafold3/commit/23e3d46d4ca126e8731e8c0cbb5673e9a848ceb5, using Python 3.12. Finishing pip install . --no-deps after pip install -r dev-requirements.txt. When ran build_data, still encountered the issue: ModuleNotFoundError: No module named 'alphafold3.cpp'
