### ISSUE TITLE
Invalid '_entity.' loop error

### ISSUE THREAD

**Issue by FilipSchymik** [google-deepmind/alphafold3#471]
Hello,
I am running a large scale alphafold3 pipeline on a HPC cluster. I encounter what seems like a rare error, since it only happened twice in hundred thousand predictions I run.

Error message:

```
Traceback (most recent call last):
    File "/app/alphafold/run_alphafold.py", line 895, in <module>
      app.run(main)
    File "/alphafold3_venv/lib/python3.11/site-packages/absl/app.py", line 308, in run
      _run_main(main, args)
    File "/alphafold3_venv/lib/python3.11/site-packages/absl/app.py", line 254, in _run_main
      sys.exit(main(argv))
               ^^^^^^^^^^
    File "/app/alphafold/run_alphafold.py", line 877, in main
      process_fold_input(
    File "/app/alphafold/run_alphafold.py", line 720, in process_fold_input
      all_inference_results = predict_structure(
                              ^^^^^^^^^^^^^^^^^^
    File "/app/alphafold/run_alphafold.py", line 450, in predict_structure
      featurised_examples = featurisation.featurise_input(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/data/featurisation.py", line 91, in featurise_input
      batch = data_pipeline.process_item(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/model/pipeline/pipeline.py", line 352, in process_item
      batch_templates = features.Templates.compute_features(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/model/features.py", line 771, in compute_features
      struc = structure.from_mmcif(
              ^^^^^^^^^^^^^^^^^^^^^
    File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/structure/parsing.py", line 443, in from_mmcif
      return from_parsed_mmcif(
             ^^^^^^^^^^^^^^^^^^
    File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/structure/parsing.py", line 358, in from_parsed_mmcif
      chains, residues, atoms = get_tables(
                                ^^^^^^^^^^^
    File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/structure/parsing.py", line 1325, in get_tables
      atom_site_all_models, layout = mmcif_utils.filter(
                                     ^^^^^^^^^^^^^^^^^^^
  ValueError: Invalid '_entity.' loop. len(id)=1, len(type)=0
```

Originally I build the MSA using mmseqs2, and found templates and run inference in the default way, but the error is reproducible (for me) even when running full data pipeline + inference starting just from bare json file with sequence. 

I am using commit `6cf8255`.

I tried to manually check the 4 templates that were found but I have not found anything wrong so far.  

Here is the input .json file causing the error:

```json
{
  "name": "MGYG000271635_00828",
  "sequences": [
    {
      "protein": {
        "id": "A",
        "sequence": "MFRQRMRYLRQQVSICFAPNDQKPGKINEFMFGRIGRYHNGIYNFKTGYAYTI"
      }
    }
  ],
  "modelSeeds": [1],
  "dialect": "alphafold3",
  "version": 3
}
```
Deleting 1l7i.cif from the templates resolved the error, but I am still not sure what is wrong with it.

**Comment by Augustin-Zidek** [comment]
Sorry for the late response. 

I am going to reproduce this on our side and get back to you. It looks like a corrupted template mmCIF, but I need to find what is corrupting it because if I try loading the vanilla `1L7I` I am not seeing the error.

**Comment by Augustin-Zidek** [comment]
I can repro on our side. This is a bug in `CifDict`, in particular how we save CIF files and treat double quotes within double quoted CIF tokens.

This is the table causing the issue (note the double quotes in the double-quote-quoted token):

```cif
_entity.id               1
_entity.pdbx_description "chimera of Fab2C4: "humanized" murine monoclonal antibody"
_entity.type             polymer
```

One possible workaround is to change this to:

```cif
_entity.id               1
_entity.pdbx_description 'chimera of Fab2C4: "humanized" murine monoclonal antibody'
_entity.type             polymer
```

We produce the mmCIF by reading the `1L7I` mmCIF, then extracting a single chain out of it, then saving it again. When we save the mmCIF, we introduce this syntax issue, which in turn causes the parser to later fail when it tries to load the processed template mmCIF.

I will send a fix tomorrow. Many thanks for reporting.

**Comment by FilipSchymik** [comment]
Thank you for the response and the fix. Have a great day.

**Comment by Augustin-Zidek** [comment]
Fixed in https://github.com/google-deepmind/alphafold3/commit/722437b4ff6f2a30d186b33c66ea1b7e0d455757

**Comment by ypczuchr** [comment]
Dear @Augustin-Zidek 

I have a (maybe stupid) question - how to apply this patch? I have pulled the newest commit for alphafold (2e2ffc1) and installed it with the commands below into the unpacked Apptainer container

```
source /alphafold3_venv/bin/activate
cd /path/to/repository
python3 -m pip install -U --prefix /alphafold3_venv .
```

All Python files have been installed properly (I can see changes in `.py` files based on other commits), but I still get this error. Should I rebuild alphafold3 somehow differently?

Best regards,
Maciej
